---
- name: Update cache for Debian
  apt:
    upgrade: safe
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install Dependencies for Debian
  apt:
    name: '{{item}}'
    state: present
    install_recommends: no
  with_items:
    - git
    - curl
    - libreadline-dev
    - pkg-config
    - autoconf
    - automake
    - build-essential
    - libmysqlclient-dev
    - libssl-dev
    - python3
    - python3-dev
    - python3-venv
    - openjdk-8-jdk-headless
    - libxml2-dev
    - libcurl4-openssl-dev
    - libxslt1-dev
    - re2c
    - bison
    - libbz2-dev
    - libreadline-dev
    - libssl-dev
    - gettext
    - libgettextpo-dev
    - libicu-dev
    - libmhash-dev
    - libmcrypt-dev
    - libgd-dev
    - libtidy-dev
  when: ansible_os_family == 'Debian'

- name: Remove conflict with Dependencies for RedHat
  yum:
    name: '{{ item }}'
    state: removed
  with_items:
    - mariadb*

- name: Install Repositories for RedHat
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
    - https://centos7.iuscommunity.org/ius-release.rpm
    - epel-release
  when: ansible_os_family == 'RedHat'

- name: Install Dependencies for RedHat
  yum:
    name: '{{ item }}'
    state: present
    update_cache: true
  with_items:
    - git
    - curl
    - readline-devel
    - pkgconfig
    - autoconf
    - automake
    - openssl-devel
    - "@Development Tools"
    - kernel-devel
    - kernel-headers
    - mysql-community-devel
    - python36u
    - python36u-devel
    - python36u-libs
    - java-1.8.0-openjdk-headless
    - libxml2-devel
    - libcurl
    - libcurl-devel
    - libxslt
    - libxslt-devel
    - re2c
    - bison
    - bzip2-devel
    - gettext
    - gettext-devel
    - gettext-libs
    - libicu-devel
    - mhash-devel
    - libmcrypt-devel
    - gd-devel
    - libtidy-devel
  when: ansible_os_family == 'RedHat'
