---
- name: restart mysql
  action: systemd name=mysql state=restarted
  when: ansible_os_family == 'Ubuntu'

- name: restart mysql
  action: systemd name=mysqld state=restarted
  when: ansible_os_family == 'RedHat'


