---
- apt:
    name: nginx
    state: present
  when: ansible_os_family == 'Debian'

- yum:
    name: nginx
    state: present
    update_cache: true
  when: ansible_os_family == 'RedHat'

- copy:
    src: ../files/nginx.php.conf
    dest: /etc/nginx/nginx.php.conf
    owner: root
    mode: 644

- copy:
    src: ../files/fastcgi_params
    dest: /etc/nginx/fastcgi_params
    owner: root
    mode: 644

- copy:
    src: ../files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    mode: 644
  notify:
    - restart nginx

- name: service nginx enabled
  systemd:
    name: nginx
    enabled: true

- name: service nginx started
  systemd:
    name: nginx
    state: started
